CREATE TABLE lhg_owner.DATABASES(
   I_DATABASES bigserial NOT null,
   NOME VARCHAR (100) NOT NULL,
   EMAIL VARCHAR (100),
   CONTATO VARCHAR(13),
   CPF VARCHAR (11),
   CNPJ VARCHAR (14),	
   ATIVO CHAR(1) DEFAULT 'S',
   AUD_DH_CRIACAO TIMESTAMP DEFAULT NOW(),
   AUD_DH_ALTERADO_POR TIMESTAMP,
   AUD_DH_ALTERACAO TIMESTAMP,
   primary key(I_DATABASES)
);


CREATE TABLE lhg_owner.USUARIO(
   I_USUARIO bigserial NOT null,
   I_DATABASES bigint NOT null,
   NOME VARCHAR (100) NOT NULL,
   EMAIL VARCHAR (100),
   CONTATO VARCHAR(13),
   CPF VARCHAR (11),
   CNPJ VARCHAR (14),	
   ATIVO CHAR(1) DEFAULT 'S',
   USUARIO VARCHAR(30) NOT NULL,
   SENHA VARCHAR(20) NOT NULL,	
   AUD_DH_CRIACAO TIMESTAMP DEFAULT NOW(),
   AUD_DH_ALTERADO_POR TIMESTAMP,
   AUD_DH_ALTERACAO TIMESTAMP,
   primary key(I_USUARIO),
   CONSTRAINT fk_database
      FOREIGN KEY(I_DATABASES) 
	  REFERENCES lhg_owner.DATABASES(I_DATABASES)
);


CREATE TABLE lhg_owner.USUARIO_PERMISSOES(
   I_PERMISSAO bigserial NOT null,
   I_DATABASES bigint NOT NULL,
   I_USUARIO bigint NOT NULL,
   ATIVO CHAR(1) DEFAULT 'S',
   NIVEL CHAR(1),
   AUD_DH_CRIACAO TIMESTAMP DEFAULT NOW(),
   AUD_DH_ALTERADO_POR TIMESTAMP,
   AUD_DH_ALTERACAO TIMESTAMP,
   primary key(I_PERMISSAO,I_DATABASES,I_USUARIO),
   CONSTRAINT fk_database FOREIGN KEY(I_DATABASES) REFERENCES lhg_owner.DATABASES(I_DATABASES),
   CONSTRAINT fk_usuario  FOREIGN KEY(I_USUARIO)   REFERENCES lhg_owner.USUARIO(I_USUARIO)
);

CREATE TABLE lhg_owner.SERVICOS(
   I_SERVICOS bigserial NOT null,
   I_DATABASES bigint NOT NULL,
   I_USUARIO bigint NOT NULL,
   DESCRICAO VARCHAR(150) NOT NULL,
   VALOR DECIMAL NOT NULL,
   AUD_DH_CRIACAO TIMESTAMP DEFAULT NOW(),
   AUD_DH_ALTERADO_POR TIMESTAMP,
   AUD_DH_ALTERACAO TIMESTAMP,
   ATIVO CHAR(1) DEFAULT 'S',
   primary key(I_SERVICOS),
   CONSTRAINT fk_database FOREIGN KEY(I_DATABASES) REFERENCES lhg_owner.DATABASES(I_DATABASES),
   CONSTRAINT fk_usuario  FOREIGN KEY(I_USUARIO)   REFERENCES lhg_owner.USUARIO(I_USUARIO)
);

CREATE TABLE lhg_owner.CLIENTE(
   I_CLIENTES bigserial NOT null,
   I_DATABASES bigint NOT NULL,
   I_USUARIO bigint NOT NULL,
   NOME VARCHAR(150) NOT NULL,
   EMAIL VARCHAR (100),
   CONTATO VARCHAR(13),
   CPF VARCHAR (11),
   CNPJ VARCHAR (14),	
   ATIVO CHAR(1) DEFAULT 'S',
   AUD_DH_CRIACAO TIMESTAMP DEFAULT NOW(),
   AUD_DH_ALTERADO_POR TIMESTAMP,
   AUD_DH_ALTERACAO TIMESTAMP,
   primary key(I_CLIENTES),
   CONSTRAINT fk_database FOREIGN KEY(I_DATABASES) REFERENCES lhg_owner.DATABASES(I_DATABASES),
   CONSTRAINT fk_usuario  FOREIGN KEY(I_USUARIO)   REFERENCES lhg_owner.USUARIO(I_USUARIO)
);


CREATE TABLE lhg_owner.CLIENTE_SERVICO_SOLICITACAO(
   I_SERVICOS_CLIENTES bigserial NOT null,
   I_CLIENTES bigint NOT null,
   I_SERVICOS bigint NOT null,
   I_DATABASES bigint NOT NULL,
   I_USUARIO bigint NOT NULL,
   AUD_DH_CRIACAO TIMESTAMP DEFAULT NOW(),
   AUD_DH_ALTERADO_POR TIMESTAMP,
   AUD_DH_ALTERACAO TIMESTAMP,
   primary key(I_SERVICOS_CLIENTES),
   CONSTRAINT fk_database FOREIGN KEY(I_DATABASES) REFERENCES lhg_owner.DATABASES(I_DATABASES),
   CONSTRAINT fk_usuario  FOREIGN KEY(I_USUARIO)   REFERENCES lhg_owner.USUARIO(I_USUARIO),
   CONSTRAINT fk_cliente  FOREIGN KEY(I_CLIENTES) REFERENCES lhg_owner.CLIENTE(I_CLIENTES),
   CONSTRAINT fk_servicos FOREIGN KEY(I_SERVICOS) REFERENCES lhg_owner.SERVICOS(I_SERVICOS)
);


